Rails.application.routes.draw do
  get 'users/home'
  get 'users/profile'
  get 'users/following'
  get 'users/followers'
  get 'users/new'
  get 'users/edit'
  get 'users/create'
  get 'users/update'
  get 'users/destroy'
  get 'followers/index'
  get 'followers/create'
  get 'followers/destroy'
  get 'messages/index'
  get 'messages/create'
  get 'events/index'
  get 'events/new'
  get 'events/create'
  get 'events/show'
  get 'events/edit'
  get 'events/update'
  get 'events/destroy'
  get 'messages/get'
  get 'messages/post'
  get 'messages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
